### PR TITLE
Fix typos in the 'Share To & Widget Extensions' section

### PR DESCRIPTION
**Pull request by Ludovic-Iafrate**
Change "hardly" to "strongly" and fix other small typos.
See https://lumapps.slack.com/archives/C01SNJXS6BT/p1627912808001200

### CODE REVIEW

**Review by gregorycat — APPROVED** [review]
Thanks for the proofreading :+1:

**Comment by gregorycat** [comment]
Sadly you'll have to respect the Commit message rules define in this repo : you can check this here : https://github.com/lumapps/commit-message-validator#commit-message-format

**Comment by Ludovic-Iafrate** [comment]
I'm not sure how to do that. 
Do I have to recommit something? (as mentioned in Slack this is the first time ever I created a PR)

**Comment by Ludovic-Iafrate** [comment]
docs(doc-lumapps-extensions-templates): Fix typos in the 'Share To & Widget Extensions' section

Change "hardly" to "strongly" and fix other small typos.
See https://lumapps.slack.com/archives/C01SNJXS6BT/p1627912808001200

**Comment by gregorycat** [comment]
It's not just changing your comment it's your commit you have to edit, I'll do it for you :smiley:

**Pull request merged**
